"""Stable S4 runtime contract facade."""

from . import s4_packet_contracts as _packet
from . import s4_accepted_contracts as _accepted
from .s4_contract_core import *
from .s4_packet_contracts import *
from .s4_accepted_contracts import *
from .s4_runtime_contracts import *


# Preserve the original single-module forward type lookup.
_packet.S4SourceRevisionPair = _accepted.S4SourceRevisionPair


__all__ = [
    'S4_PACKET_SCHEMA_ID',
    'S4_AUTHORITY_MODE',
    'S4_STATUS',
    'PACKET_ID_PREFIX',
    'PACKET_ID_GRAMMAR',
    'ANCHOR_REF_PREFIX',
    'RECEIPT_REF_PREFIX',
    'HISTORY_REF_PREFIX',
    'RAW_REF_PREFIX',
    'VERIFICATION_REF_PREFIX',
    'GENESIS_HASH',
    'ADJUDICATION_RECORD_REF',
    'HASH_CANONICALIZATION',
    'S4RuntimeContractError',
    'S4RuntimeImplementationError',
    'R5S4ValidationIssue',
    'R5S4ValidationResult',
    'ENSEMBLE_PROJECTION_STATES',
    'BASELINE_STATES',
    'RECHECK_REQUIRED_STATES',
    'ASSESSMENT_REASON_CODES',
    'VERIFICATION_DIMENSIONS',
    'VERIFICATION_RESULTS',
    'VERIFICATION_FAILURE_CODES',
    'CONFLICT_RELATIONS',
    'CONFLICT_DISPLAY_STATES',
    'NON_HIDEABLE_RELATIONS',
    'ADJUDICATION_OUTCOMES',
    'ATTEMPT_ROLES',
    'RAW_OUTPUT_FORMATS',
    'FALLBACK_POLICIES',
    'PD_WORDING_STATES',
    'MONITORING_PRIORITIES',
    'SEVERITIES',
    'SEVERITIES_ZH',
    'DOMAINS',
    'CHANGE_KINDS',
    'CHANGE_CAUSES',
    'HISTORY_ENTRY_KINDS',
    'MODEL_EVIDENCE_ROLES',
    'MODEL_EVIDENCE_ADJUDICATION_STATES',
    'ORDINAL_ZH',
    'DOMAIN_ZH',
    'SEVERITY_ZH_BY_SEVERITY',
    'SEVERITY_MAPPING',
    'CHANGE_KIND_ZH',
    'BASELINE_STATE_ZH',
    'RECHECK_ZH',
    'VERIFICATION_RESULT_ZH',
    'VERIFICATION_FAILURE_ZH',
    'CONFLICT_RELATION_ZH',
    'ADJUDICATION_OUTCOME_ZH',
    'PD_WORDING_ZH',
    'CONSENSUS_ZH',
    'ADJUDICATION_STATUS_ZH',
    'HISTORY_SUMMARY_ZH',
    'BASIS_ZH',
    'JOURNEY_LINK_ZH',
    'JOURNEY_UNAVAILABLE_REASON_ZH',
    'FORBIDDEN_AUDIENCE_TOKENS',
    'AUDIT_ONLY_LEAVES',
    'QUERY_TASK_FORBIDDEN_KEYS',
    'SEVEN_DIMENSIONS',
    'AUDIENCE_CONTRACT_ID',
    'SUPPORTING_OUTCOMES',
    'NEAREST_FALLBACK_TOKENS',
    'SOURCE_AVAILABILITY_STATES',
    'UNAVAILABLE_REASONS',
    'D09_MARKER_PREFIX',
    'D10_MARKER_PREFIX',
    'BASELINE_ROW_GRAMMAR',
    'PROJECT_REF_GRAMMAR',
    'RUN_REF_GRAMMAR',
    'SNAPSHOT_REF_GRAMMAR',
    'CUTOFF_REF_GRAMMAR',
    'SOURCE_REVISION_GRAMMAR',
    'R5S4RiskIdentity',
    'R5S4WorkerView',
    'R5S4RawOutputArtifact',
    'R5S4BaselineItemProjection',
    'R5S4BaselineRow',
    'R5S4ConflictRow',
    'R5S4VerificationRow',
    'R5S4AdjudicationRow',
    'R5S4QueryDraftRow',
    'R5S4JourneyLink',
    'R5S4HistoryEntry',
    'R5S4HistoryLog',
    'R5S4AudienceBaselineRow',
    'R5S4AudienceWorkerSummary',
    'R5S4AudienceInspector',
    'R5S4AuditWorkerRow',
    'R5S4VerificationAuditRow',
    'R5S4DigestContextView',
    'R5S4ModelEvidenceRef',
    'R5S4AuditInspector',
    'R5S4AuthorityPacket',
    'S4AcceptedHistoryState',
    'S4SourceRevisionPair',
    'S4AcceptedAdjudicatorBinding',
    'S4AcceptedBaselineItem',
    'S4AcceptedQueryDraft',
    'S4AcceptedRiskIdentity',
    'S4AttemptAuthorityRow',
    'S4JourneyTargetIdentity',
    'S4ModelEvidencePermit',
    'S4AcceptedAuthorityAnchor',
    'R5S4RawOutputInput',
    'R5S4AdjudicatorInput',
    'R5S4SyntheticAudienceLabels',
    'R5S4SourceInput',
    'R5S4RuntimeInput',
    'R5S4BuildState',
]
