"""mm_r5 -- R5 medical monitoring exact typed contract surface (synthetic,
offline, R4 read-only by later slices).

R5 S1 layer 1 (worker_01): the frozen exact typed contract surface and
canonical hashing of ``medical-monitoring-r5-exact-contract-v0.3.1``.

Public surface:

* All 29 immutable typed objects and the 28 closed enums of
  ``exact_contract.json`` with fail-closed construction
  (:mod:`mm_r5.contracts`).
* Deterministic canonical serialization and content addressing
  (:mod:`mm_r5.canonical`): NFC normalization, sorted unordered refs,
  non-hash-field exclusion and tamper rejection.
* The deferred-leaf registry (:mod:`mm_r5.contracts`): leaves whose fields
  have no upstream R4 public authority yet are fully typed and constructible
  as references/contracts, honestly marked, never pretending later-stage
  data exists.
* The frozen audience encoding registry / audience lexicon contract
  constants (``build_audience_encoding_registry`` /
  ``build_audience_lexicon``) with explicit pin status.
* The accepted S2 synthetic/offline authority-packet contract, real R4 typed
  pipeline builder and renderer-neutral thin-slice projection. These APIs
  expose exact identity/source traversal only; later-stage Inspector evidence,
  quantitative measures and user-interface behavior remain deferred.
* The Slice-07C-3 publication authority seam: typed run/input assembly,
  existing S4 builder/validator reuse and deterministic S4-to-product member
  joins (:mod:`mm_r5.r5_publication_authority`).

The package never starts a service (port 8911 stays stopped; no browser or
network). R4 is imported only by the explicit S2 authority builder.
"""

from .canonical import (
    R5CanonicalError,
    canonical_json,
    canonical_object_hash,
    content_hash,
    is_sha256_hex,
    object_to_core,
    register_object_fields,
    sha256_hex,
)
from .contracts import (
    APPLICABILITY_STATES,
    AXIS_MODES,
    CHANGE_CAUSES,
    CHANGE_KINDS,
    CONTRACT_CONSTANT_PIN_STATUS,
    COVERAGE_STATES,
    DATE_STATES,
    DEFERRED_CONTRACT_BY_ID,
    DEFERRED_CONTRACT_SPECS,
    DENOMINATOR_KINDS,
    DENOMINATOR_STATES,
    DOMAIN_ENCODING_ITEMS,
    DOMAIN_SUBTYPE_MATRIX,
    DOMAINS,
    EVENT_FORBIDDEN_SHAPES,
    EVENT_SHAPES,
    FORBIDDEN_TERMS,
    JOURNEY_SUBTYPES,
    LEGACY_DOMAIN_POLICY,
    LEGACY_MAPPING_STATES,
    LEGACY_SEVERITY_MAPPING,
    LEGACY_TREATMENT_KINDS,
    LEGACY_TREATMENT_MAPPING_ITEMS,
    LEXICON_ITEMS,
    LINE_STYLES,
    MATCH_STATES,
    MEASURE_UNITS,
    NUMERATOR_KINDS,
    PENDING_ITEM_KINDS,
    PROJECTION_KINDS,
    R4_AUTHORITY_SEVERITY_VOCABULARY,
    R5AEMHMatchHistory,
    R5AudienceEncodingRegistry,
    R5AudienceLexicon,
    R5AuthorityReceipt,
    R5CenterMapCell,
    R5CenterMapProjection,
    R5ChangeBand,
    R5ContractError,
    R5CurrentRiskSet,
    R5DeepLinkState,
    R5DeferredContract,
    R5DomainEncodingItem,
    R5FilterState,
    R5HashMismatchError,
    R5JourneyEvent,
    R5JourneyTrack,
    R5LegacyTreatmentMappingItem,
    R5LexiconItem,
    R5PageState,
    R5PendingDateItem,
    R5ProjectCockpitProjection,
    R5ProjectionInstance,
    R5QuantitativeMeasure,
    R5ReturnContext,
    R5RiskAnchor,
    R5RiskInspectorProjection,
    R5ScrollState,
    R5SeverityLexiconItem,
    R5SortState,
    R5SubjectWorkspaceState,
    R5TemporalSpineProjection,
    R5VisitNode,
    R5_CONTRACT_SHA256,
    R5_CONTRACT_SCHEMA_ID,
    R5_EXACT_CONTRACT_ARTIFACT_SHA256,
    RATE_STATES,
    RISK_OVERLAY_SHAPE,
    SEVERITIES,
    SEVERITY_LEXICON_ITEMS,
    SEVERITY_TO_ZH,
    SEVERITY_ZH,
    SORT_DIRECTIONS,
    SORT_KEYS,
    SYMPTOM_EFFICACY_SUBTYPES,
    SourceRevisionContentPair,
    UNKNOWN_DOMAIN_POLICY,
    VISIBILITY_STATES,
    VISIT_KINDS,
    WORKSPACE_VIEWS,
    ZH_TO_SEVERITY,
    build_audience_encoding_registry,
    build_audience_lexicon,
    deferred_contract,
    deferred_fields_for,
    deferred_leaf_objects,
    enum_values,
    is_deferred_field,
    is_r5_object,
    known_object_names,
    legacy_severity_to_r5,
    severity_to_zh,
    validate_object,
    validate_severity_authority,
    zh_to_severity,
)
from .authority_adapter import (
    DEFAULT_D10_AUTHORITY_ADAPTER_VARIANT,
    R5_CONTRACTS_SOURCE,
    R5_PROJECTION_KINDS,
    AuthorityReceiptError,
    D10AuthorityAdapterVariant,
    authority_receipt_dict,
    build_authority_receipt,
    compute_visibility_decision_hash,
    d10_visibility_decision_canonical_dict,
    projectable_partition,
    verify_authority_receipt,
)
from .s2_contracts import (
    AUTHORITY_MODE_S2,
    FROZEN_INVARIANT_ERROR_CODES,
    MODEL_EVIDENCE_VISIBILITIES,
    RESOLUTION_STATES,
    R5S2AuthorityPacket,
    R5S2CenterBinding,
    R5S2InspectorBinding,
    R5S2ProjectRiskBinding,
    R5S2SourceBinding,
    R5S2TemporalBinding,
    S2CanonicalError,
    S2ContractError,
    S2HashMismatchError,
    S2InvariantError,
    compute_packet_content_hash,
    compute_packet_id,
    is_s2_authority_packet,
    validate_s2_authority_packet,
)
from .s2_authority_builder import (
    S2AuthorityBuilderError,
    build_s2_authority_packet,
    build_synthetic_d10_envelope,
    resolve_center_pattern_member,
    resolve_source_authority,
)
from .s2_thin_slice import (
    R5S2SourceResolution,
    R5S2ThinSliceProjection,
    ThinSliceProjectionError,
    is_thin_slice_projection,
    project_thin_slice,
    resolve_exact_source,
    validate_thin_slice,
)
from .r5_publication_authority import (
    R5AuthorityPacket,
    R5PublicationAuthorityBridge,
    R5PublicationAuthorityError,
    R5PublicationAuthorityInput,
    R5PublicationAuthorityInputAssembler,
    R5PublicationRawBytes,
    R5PublicationRunIdentity,
)


__version__ = "0.1.0"

__all__ = [
    "APPLICABILITY_STATES",
    "AuthorityReceiptError",
    "AXIS_MODES",
    "CHANGE_CAUSES",
    "CHANGE_KINDS",
    "CONTRACT_CONSTANT_PIN_STATUS",
    "COVERAGE_STATES",
    "DATE_STATES",
    "DEFAULT_D10_AUTHORITY_ADAPTER_VARIANT",
    "DEFERRED_CONTRACT_BY_ID",
    "DEFERRED_CONTRACT_SPECS",
    "DENOMINATOR_KINDS",
    "DENOMINATOR_STATES",
    "D10AuthorityAdapterVariant",
    "DOMAIN_ENCODING_ITEMS",
    "DOMAIN_SUBTYPE_MATRIX",
    "DOMAINS",
    "EVENT_FORBIDDEN_SHAPES",
    "EVENT_SHAPES",
    "FORBIDDEN_TERMS",
    "JOURNEY_SUBTYPES",
    "LEGACY_DOMAIN_POLICY",
    "LEGACY_MAPPING_STATES",
    "LEGACY_SEVERITY_MAPPING",
    "LEGACY_TREATMENT_KINDS",
    "LEGACY_TREATMENT_MAPPING_ITEMS",
    "LEXICON_ITEMS",
    "LINE_STYLES",
    "MATCH_STATES",
    "MEASURE_UNITS",
    "NUMERATOR_KINDS",
    "PENDING_ITEM_KINDS",
    "PROJECTION_KINDS",
    "R4_AUTHORITY_SEVERITY_VOCABULARY",
    "R5_CONTRACT_SCHEMA_ID",
    "R5_CONTRACT_SHA256",
    "R5_CONTRACTS_SOURCE",
    "R5_EXACT_CONTRACT_ARTIFACT_SHA256",
    "R5_PROJECTION_KINDS",
    "R5AEMHMatchHistory",
    "R5AudienceEncodingRegistry",
    "R5AudienceLexicon",
    "R5AuthorityReceipt",
    "R5CanonicalError",
    "R5CenterMapCell",
    "R5CenterMapProjection",
    "R5ChangeBand",
    "R5ContractError",
    "R5CurrentRiskSet",
    "R5DeepLinkState",
    "R5DeferredContract",
    "R5DomainEncodingItem",
    "R5FilterState",
    "R5HashMismatchError",
    "R5JourneyEvent",
    "R5JourneyTrack",
    "R5LegacyTreatmentMappingItem",
    "R5LexiconItem",
    "R5PageState",
    "R5PendingDateItem",
    "R5ProjectCockpitProjection",
    "R5ProjectionInstance",
    "R5QuantitativeMeasure",
    "R5ReturnContext",
    "R5RiskAnchor",
    "R5RiskInspectorProjection",
    "R5ScrollState",
    "R5SeverityLexiconItem",
    "R5SortState",
    "R5SubjectWorkspaceState",
    "R5TemporalSpineProjection",
    "R5VisitNode",
    "RATE_STATES",
    "RISK_OVERLAY_SHAPE",
    "SEVERITIES",
    "SEVERITY_LEXICON_ITEMS",
    "SEVERITY_TO_ZH",
    "SEVERITY_ZH",
    "SORT_DIRECTIONS",
    "SORT_KEYS",
    "SYMPTOM_EFFICACY_SUBTYPES",
    "SourceRevisionContentPair",
    "UNKNOWN_DOMAIN_POLICY",
    "VISIBILITY_STATES",
    "VISIT_KINDS",
    "WORKSPACE_VIEWS",
    "ZH_TO_SEVERITY",
    "build_audience_encoding_registry",
    "build_audience_lexicon",
    "build_authority_receipt",
    "authority_receipt_dict",
    "canonical_json",
    "canonical_object_hash",
    "content_hash",
    "compute_visibility_decision_hash",
    "d10_visibility_decision_canonical_dict",
    "deferred_contract",
    "deferred_fields_for",
    "deferred_leaf_objects",
    "enum_values",
    "is_deferred_field",
    "is_r5_object",
    "is_sha256_hex",
    "known_object_names",
    "legacy_severity_to_r5",
    "object_to_core",
    "projectable_partition",
    "register_object_fields",
    "severity_to_zh",
    "sha256_hex",
    "validate_object",
    "validate_severity_authority",
    "verify_authority_receipt",
    "zh_to_severity",
]

__all__ += [
    "AUTHORITY_MODE_S2",
    "FROZEN_INVARIANT_ERROR_CODES",
    "MODEL_EVIDENCE_VISIBILITIES",
    "RESOLUTION_STATES",
    "R5S2AuthorityPacket",
    "R5S2CenterBinding",
    "R5S2InspectorBinding",
    "R5S2ProjectRiskBinding",
    "R5S2SourceBinding",
    "R5S2SourceResolution",
    "R5S2TemporalBinding",
    "R5S2ThinSliceProjection",
    "S2AuthorityBuilderError",
    "S2CanonicalError",
    "S2ContractError",
    "S2HashMismatchError",
    "S2InvariantError",
    "ThinSliceProjectionError",
    "build_s2_authority_packet",
    "build_synthetic_d10_envelope",
    "compute_packet_content_hash",
    "compute_packet_id",
    "is_s2_authority_packet",
    "is_thin_slice_projection",
    "project_thin_slice",
    "resolve_center_pattern_member",
    "resolve_exact_source",
    "resolve_source_authority",
    "validate_s2_authority_packet",
    "validate_thin_slice",
]

__all__ += [
    "R5AuthorityPacket",
    "R5PublicationAuthorityBridge",
    "R5PublicationAuthorityError",
    "R5PublicationAuthorityInput",
    "R5PublicationAuthorityInputAssembler",
    "R5PublicationRawBytes",
    "R5PublicationRunIdentity",
]
