"""D05 visit-schedule domain compatibility facade."""

from . import visit_schedule_binding as _binding

from .visit_schedule_types import *
from .visit_schedule_types import (
    _validate_nonempty,
    _validate_optional_str,
    _freeze_tuple,
    _canonical_sorted,
    _require_member,
    _date_precision,
    _day_date,
    _day_interval,
    _coarsest_precision,
    _tzinfo,
    _parse_instant,
    _day_instant_interval,
    _interval_compare,
    _payload_ids,
    _marker_id_list,
)
from .visit_schedule_records import *
from .visit_schedule_records import (
    _validate_record_dates,
    _record_content_hash,
    _member_effective_interval,
    _derived_bundle_interval,
)
from .visit_schedule_binding import *
from .visit_schedule_binding import (
    _anchor_gate,
    _ref_ctx,
    _producer_stable_event_key,
    _anchor_binding_verdict,
)
from .visit_schedule_gates import *

# Anchor binding constructs a gate only after the full domain surface loads.
_binding.ScheduleGate = ScheduleGate

__all__ = ['D05_DOMAIN', 'D05_UNIT_ALGO_VERSION', 'D05_RULE_LINEAGE_DEFAULT', 'D05_SOURCE_IDENTITY_ALGORITHM_VERSION', 'VISIT_KINDS', 'VISIT_SCHEDULED', 'VISIT_TRIGGERED', 'VISIT_CONTINGENT', 'VISIT_REPEAT_ALLOWED', 'ACTIVITY_KINDS', 'ACTIVITY_ASSESSMENT', 'ACTIVITY_SAMPLE', 'ACTIVITY_PROCEDURE', 'ACTIVITY_CONTACT', 'ENCOUNTER_KINDS', 'ENCOUNTER_ONSITE', 'ENCOUNTER_REMOTE', 'ENCOUNTER_HOSPITAL', 'ENCOUNTER_HOME', 'ENCOUNTER_UNSCHEDULED', 'ENCOUNTER_UNKNOWN', 'MODALITIES', 'MODALITY_ONSITE', 'MODALITY_REMOTE', 'MODALITY_PHONE', 'MODALITY_HOME', 'MODALITY_HOSPITAL', 'MODALITY_OTHER', 'MODALITY_UNKNOWN', 'PRECISIONS', 'PRECISION_MINUTE', 'PRECISION_HOUR', 'PRECISION_DAY', 'PRECISION_MONTH', 'PRECISION_YEAR', 'PRECISION_UNKNOWN', 'SUB_DAY_PRECISIONS', 'DATE_ORIGINS', 'DATE_ORIGIN_RECORDED', 'DATE_ORIGIN_DERIVED', 'SCOPE_STATUSES', 'SCOPE_IN_SCOPE', 'SCOPE_OUT_OF_CUTOFF', 'SCOPE_BOUNDARY', 'SCOPE_NOT_EVALUABLE', 'APPLICABILITY_STATUSES', 'APPLICABILITY_UNIQUE_ACTIVE', 'APPLICABILITY_MULTI_FEASIBLE_BOUNDARY', 'APPLICABILITY_NOT_EVALUABLE', 'TRANSITION_RULES', 'TRANSITION_NEW_ENROLLMENT_ONLY', 'TRANSITION_EXISTING_CONTINUE_OLD', 'TRANSITION_ALL_SWITCH', 'TRANSITION_NEXT_VISIT_SWITCH', 'TRANSITION_RECONSENT_SWITCH', 'TRANSITION_OTHER_EXPLICIT', 'TRANSITION_UNDETERMINED', 'GATE_KINDS', 'GATE_APPLICABILITY', 'GATE_ROUTING', 'GATE_ANCHOR', 'GATE_CUTOFF_SCOPE', 'GATE_STATES', 'GATE_OPEN', 'GATE_CLOSED', 'GATE_DECISION_STATUSES', 'GATE_DECISION_BOUNDARY', 'GATE_DECISION_NOT_EVALUABLE', 'GATE_DECISION_RESOLVED', 'RELATION_TYPES', 'RELATION_FIXED_REFERENCE', 'RELATION_PRIOR_ACTUAL_VISIT', 'RELATION_FIRST_IP_DOSE', 'RELATION_RANDOMIZATION', 'RELATION_CONSENT', 'RELATION_OTHER_VERIFIED_PROTOCOL_ANCHOR', 'PRODUCER_RELATION_TYPES', 'INTERNAL_RELATION_TYPES', 'UNIT_KINDS', 'UNIT_VISIT_OCCURRENCE', 'UNIT_VISIT_TIMING', 'UNIT_VISIT_ORDER', 'UNIT_ACTIVITY_OCCURRENCE', 'UNIT_ACTIVITY_TIMING', 'UNIT_ACTUAL_ASSIGNMENT', 'UNIT_SCHEDULE_CONSISTENCY', 'EPISODE_KINDS', 'EPISODE_SINGLE_CONTACT', 'EPISODE_MULTI_CONTACT', 'EPISODE_HOSPITALIZATION', 'EPISODE_REMOTE', 'EPISODE_UNSCHEDULED', 'EPISODE_UNKNOWN', 'ASSIGNMENT_SCOPES', 'ASSIGNMENT_SCOPE_SINGLE', 'ASSIGNMENT_SCOPE_MULTI', 'ASSIGNMENT_SCOPE_UNKNOWN', 'VISIT_ASSIGNMENT_STATUSES', 'VISIT_ASSIGNMENT_UNIQUE', 'VISIT_ASSIGNMENT_MULTI_FEASIBLE', 'VISIT_ASSIGNMENT_UNPLANNED_SUPPORTED', 'VISIT_ASSIGNMENT_UNASSIGNED_INCONSISTENT', 'VISIT_ASSIGNMENT_NOT_EVALUABLE', 'ACTIVITY_ASSIGNMENT_STATUSES', 'ACTIVITY_ASSIGNMENT_UNIQUE', 'ACTIVITY_ASSIGNMENT_MULTI_FEASIBLE', 'ACTIVITY_ASSIGNMENT_UNPLANNED_SUPPORTED', 'ACTIVITY_ASSIGNMENT_DUPLICATE_CONSUMPTION', 'ACTIVITY_ASSIGNMENT_NOT_EVALUABLE', 'REVERSE_COVERAGE_STATUSES', 'REVERSE_COVERAGE_CLOSED', 'REVERSE_COVERAGE_OPEN', 'OWNER_D05', 'OWNER_D03', 'OWNER_D04', 'OWNER_D06', 'OWNER_D07', 'OWNER_D08', 'OWNER_UNRESOLVED', 'OWNER_DOMAINS', 'REASON_CODES', 'REASON_VERSION_MISSING', 'REASON_VERSION_CONFLICT', 'REASON_MULTIPLE_FEASIBLE', 'REASON_SITE_ACTIVATION_MISSING', 'REASON_COHORT_OR_ARM_CONFLICT', 'REASON_TRANSITION_TIME_MISSING', 'REASON_TRANSITION_TIME_CONFLICT', 'REASON_ROUTING_COMPETITION', 'REASON_ANCHOR_MISSING', 'REASON_ANCHOR_CONFLICT', 'REASON_PRODUCER_NOT_EVALUABLE', 'REASON_TIME_ROLE_MISSING', 'REASON_TIME_ROLE_CONFLICT', 'REASON_INTERVAL_STRADDLES', 'REASON_PRECISION_INSUFFICIENT', 'REASON_TIMEZONE_MISSING', 'REASON_IDENTITY_AMBIGUOUS', 'REASON_MATURITY_RULE_MISSING', 'REASON_MAPPING_MISSING', 'REASON_SCHEDULE_MISSING', 'REASON_INVALID_RELATION_TYPE', 'REASON_WRONG_CONSUMER_DOMAIN', 'REASON_WRONG_PRODUCER_DOMAIN', 'REASON_SUBJECT_SITE_MISMATCH', 'REASON_PHASE_OR_EPISODE_MISMATCH', 'REASON_INTERVAL_MISMATCH', 'REASON_PRECISION_OR_TIMEZONE_MISMATCH', 'REASON_COVERAGE_INCOMPLETE', 'REASON_OTHER', 'CALENDAR_SEMANTICS', 'CALENDAR_DATE', 'ELAPSED_DURATION', 'STUDY_DAY', 'PROPAGATION_RULES', 'PROPAGATION_FIXED_ANCHOR', 'PROPAGATION_CHAINED_PRIOR_VISIT', 'PROPAGATION_EXPLICIT_RESCHEDULE', 'PROPAGATION_UNDEFINED', 'MISSING_ANCHOR_EFFECT_GATE', 'ANCHOR_SOURCE_ROLES', 'ANCHOR_ROLE_VISIT_SCHEDULE', 'ANCHOR_ROLE_IP_EXPOSURE', 'ANCHOR_ROLE_RANDOMIZATION', 'ANCHOR_ROLE_CONSENT', 'ANCHOR_ROLE_DISPOSITION', 'ANCHOR_ROLE_OTHER', 'INTERPRETATION_SCOPES', 'INTERPRET_SCOPE_MERGE', 'INTERPRET_SCOPE_SPLIT', 'INTERPRET_SCOPE_REPEAT', 'INTERPRET_SCOPE_RESCHEDULE', 'INTERPRET_SCOPE_TRIGGER', 'INTERPRET_SCOPE_WINDOW', 'INTERPRET_SCOPE_OTHER', 'INTERPRETATION_PREDICATES', 'PREDICATE_TRUE', 'PREDICATE_FALSE', 'PREDICATE_BOUNDARY', 'PREDICATE_NOT_EVALUABLE', 'MARKER_STATUS_HINTS', 'STATUS_UPCOMING', 'STATUS_DUE', 'STATUS_EVALUATED', 'STATUS_PENDING_ASSIGNMENT', 'STATUS_PENDING_TIME', 'ANCHOR_STATES', 'ANCHOR_STATE_DATED', 'ANCHOR_STATE_PARTIAL', 'ANCHOR_STATE_PENDING_TIME', 'ANCHOR_STATE_OUT_OF_CUTOFF', 'ScheduleSliceError', 'SnapshotAsOf', 'ClinicalEventCutoff', 'VisitAnchorRule', 'VisitWindowRule', 'EvaluationMaturityRule', 'PlannedVisitDefinition', 'PlannedActivityDefinition', 'VisitScheduleApplicabilityDecision', 'ActualEncounterRecord', 'ActualActivityRecord', 'ActualEncounterBundle', 'ActualRecordScopeDecision', 'VisitAssignmentDecision', 'ActivityAssignmentDecision', 'ActualActivityConsumptionLedger', 'TypedScheduleAnchorRef', 'AnchorBindingOutcome', 'ScheduleGate', 'GateRunAccounting', 'ScheduleInterpretationLedger', 'ScheduleEvaluationUnit', 'VisitCoverageGapNotice', 'PlannedVisitMarker', 'ActualEncounterMarker', 'VisitRiskMarker', 'VisitJourneyProjection', 'encounter_stable_object_key', 'activity_stable_object_key', 'bundle_stable_object_key', 'resolve_actual_record_scope', 'build_actual_encounter_bundle', 'validate_bundle_membership', 'bind_typed_schedule_anchor', 'anchor_binding_matches', 'validate_gate_run_accounting', 'all_gates_closed', 'schedule_evaluation_window_id', 'schedule_unit_stable_core', 'schedule_unit_classifier']
