"""R6 ModeContract and ModeOutput compatibility facade."""

from .mode_output_core import *
from .mode_output_core import (
    _copy_mapping,
    _require_non_empty_str,
    _frozen_mode_contract_rows,
    _row_by_mode,
    _reshape_mode_contract,
    _dedupe,
    _append,
    _non_empty_str,
    _truthy_flag,
    _validate_common_binding,
    _validate_silent_conversion,
    _validate_execution_basis,
    _validate_entry_conditions,
    _validate_cutoff_and_revision,
    _validate_carry_forward,
    _eligible_kinds_for_mode,
    _require_ref_mapping,
    _bind_refs_to_run,
    _check_eligibility,
    _zh_clause,
    _finding_scope,
    _finding_evidence,
    _assert_query_draft_boundary,
    _query_draft_id,
    _build_one_query_draft,
    _default_payload_for_kind,
    _numeric_near,
    _validate_numeric_payload,
    _validate_change_entries,
)
from .mode_output_pre_lock import *
from .mode_output_pre_lock import (
    _shared_payload_identity,
    _require_pre_lock_run,
    _normalize_population_scope,
    _impact_id,
    _normalize_impact_item,
    _check_id,
    _normalize_check_item,
    _normalize_revision_entry,
    _normalize_supplied_query_draft,
    _default_pre_lock_payload_for_kind,
    _validate_full_risk_payload,
    _validate_pre_lock_payload_binding,
    _validate_revision_impact_payload,
    _validate_check_package_payload,
    _validate_query_revision_package_payload,
)
from .mode_output_post_lock import *
from .mode_output_post_lock import (
    _require_post_lock_run,
    _normalize_population_totals,
    _shared_post_lock_identity,
    _reject_overwrite_metadata,
    _append_post_lock_surface_claim_codes,
    _assert_post_lock_surface_claims,
    _normalize_evidence_refs,
    _normalize_checkable_locator,
    _normalize_id_list,
    _normalize_project_summary,
    _validate_post_lock_payload_binding,
    _normalize_risk_summary,
    _site_material_id,
    _subject_material_id,
    _post_lock_check_id,
    _checklist_id_from_items,
    _report_id_from_body,
    _normalize_site_material,
    _normalize_subject_material,
    _normalize_post_lock_check_item,
    _validate_site_materials_payload,
    _validate_subject_materials_payload,
    _validate_checklist_payload,
    _validate_full_project_report_payload,
    _default_post_lock_payload_for_kind,
)
from .mode_output_orchestration import *
from .mode_output_orchestration import (
    _validate_query_payload,
)
