"""mm_r1 -- framework-neutral domain/graph/store kernel for the medical
monitoring AI-native R1 POC (synthetic fixtures only).

Public surface for workers 02-04: domain schema + state machines
(:mod:`mm_r1.domain`), Graph IR + GraphPort/CheckpointPort (:mod:`mm_r1.graph`)
and the SQLite authoritative store with atomic commit, audit chain, artifact
coverage and recovery (:mod:`mm_r1.store`).
"""

from .domain import (
    ACCEPTANCE_CHAIN,
    ACCEPTED_BY_SYSTEM_POLICY,
    NODE_TYPES,
    TERMINAL_NODE_STATUSES,
    AnalysisState,
    ArtifactCompleteness,
    ArtifactEnvelope,
    AuditEvent,
    CanonicalFact,
    Checkpoint,
    ClaimCoverageEntry,
    ClaimCoverageLedger,
    CoverageManifest,
    CoverageUnit,
    CoverageUnitStatus,
    EvidenceState,
    ExecutionBasis,
    ExecutionManifest,
    ListingSnapshot,
    ManifestNode,
    ManifestWorkUnit,
    ModeContract,
    ModelAnalysis,
    MonitoringRun,
    NodeAttempt,
    NodeRun,
    NodeStatus,
    NodeType,
    OutputState,
    ProjectionVersion,
    QueryDraft,
    ReferenceBaseline,
    ReferenceBaselineEntry,
    ReportClaim,
    ReportUnitRef,
    ReviewIssue,
    ReviewState,
    RiskCandidate,
    RiskIdentity,
    RiskInstance,
    RiskLifecycleState,
    RiskTransition,
    RunMode,
    SnapshotAcceptance,
    SnapshotAcceptanceState,
    SnapshotBaselineProof,
    SourceRevision,
    StudyProject,
    SubjectTemporalSpine,
    TemporalEvent,
    UserDisposition,
    WorkUnitRun,
    canonical_json,
    content_hash,
    from_jsonable,
    new_id,
    now_iso,
    sha256_hex,
    to_jsonable,
)
from .domain import (
    MmR1Error,
    StoreError,
    AcceptanceChainError,
    AmbiguityBlocksAcceptanceError,
    ArtifactCollisionError,
    CompletionGateError,
    GraphValidationError,
    IdempotencyConflictError,
    NodeTerminalError,
    PromotionForbiddenError,
    StaleCallbackError,
)
from .graph import (
    CheckpointPort,
    Graph,
    GraphEdge,
    GraphNode,
    GraphNodeResult,
    GraphPort,
    GraphRun,
    LocalGraphPort,
    NodeContext,
    NodeOutcome,
)
from .store import RecoveryReport, RunRecoveryState, Store
from .capability_runtime import (
    AdapterWorkEvent,
    ApiCapabilityRuntime,
    AttemptLifecycleObserver,
    AttemptIdentityError,
    AttemptStage,
    CapabilityAttemptResult,
    CapabilityPersistenceReceipt,
    CapabilityRequest,
    CapabilityRuntime,
    CapabilityRuntimeError,
    ExecutionProfile,
    HarnessCapabilityRuntime,
    HarnessIsolationBackend,
    HarnessIsolationPolicy,
    InvocationVersions,
    StaleAttemptError,
    TransportExecution,
    TransportKind,
    persist_capability_attempt,
)

__version__ = "0.1.0"
